[package]
name = "sixtyfps-viewer"
version = "0.0.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "Viewer binary for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"

[dependencies]
sixtyfps-corelib = { version = "=0.0.2", path="../../sixtyfps_runtime/corelib" }
sixtyfps-interpreter = { version = "=0.0.2", path = "../../sixtyfps_runtime/interpreter" }
sixtyfps-compilerlib = { version = "=0.0.2", path = "../../sixtyfps_compiler", features = ["display-diagnostics"] }
vtable = { version = "0.1", path="../../helper_crates/vtable" }
structopt = "0.3.14"
codemap-diagnostic = "0.1.1"
codemap = "0.1"


[[bin]]
name = "viewer"
path = "main.rs"
