[package]
name = "sixtyfps-rendering-backend-gl"
version = "0.0.2"
authors = ["SixtyFPS <info@sixtyfps.io>"]
edition = "2018"
license = "GPL-3.0-only"
description = "OpenGL rendering backend for SixtyFPS"
repository = "https://github.com/sixtyfpsui/sixtyfps"
homepage = "https://sixtyfps.io"


[lib]
path = "lib.rs"

[features]
x11 = ["winit/x11", "glutin/x11", "sixtyfps-corelib/x11"]
wayland = ["winit/wayland", "glutin/wayland", "sixtyfps-corelib/wayland"]
default = ["x11"]

[dependencies]
sixtyfps-corelib = { version = "=0.0.2", path = "../../corelib" }
lyon = { version = "0.16" }
image = { version = "0.23.10", default-features = false }
cgmath = "0.17.0"
vtable = { version = "0.1", path = "../../../helper_crates/vtable" }
pathfinder_geometry = "0.5.1"
guillotiere = "0.6"
itertools = "0.9.0"
smallvec = "1.4.1"

[target.'cfg(target_arch = "wasm32")'.dependencies]
web_sys = { version = "0.3", package = "web-sys", features=["console", "WebGlContextAttributes"] }
wasm-bindgen = { version = "0.2" }
winit = { version = "0.23", default-features = false, features = ["web-sys"] }
glow = { version = "0.6.1", features = ["web-sys"], default-features = false }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
winit = { version = "0.23", default-features = false }
glutin = { version = "0.25.1", default-features = false }
glow = { version = "0.6.1", default-features = false }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = { version = "0.24.0" }

