# LICENSE BEGIN
# This file is part of the SixtyFPS Project -- https://sixtyfps.io
# Copyright (c) 2020 Olivier Goffart <olivier.goffart@sixtyfps.io>
# Copyright (c) 2020 Simon Hausmann <simon.hausmann@sixtyfps.io>
#
# SPDX-License-Identifier: GPL-3.0-only
# This file is also available under commercial licensing terms.
# Please contact info@sixtyfps.io for more information.
# LICENSE END
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build_and_test:
    env:
      LD_LIBRARY_PATH: /home/runner/work/sixtyfps/Qt/5.12.9/gcc_64/lib
      DYLD_FRAMEWORK_PATH: /Users/runner/work/sixtyfps/Qt/5.12.9/clang_64/lib

    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Cache Qt
      if: matrix.os != 'windows-latest'
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ../Qt
        key: ${{ runner.os }}-${{ github.job }}-QtCache-5.12.9
    - name: Install Qt
      if: matrix.os != 'windows-latest'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - id: nodeversion
      run: |
          echo "::set-output name=node-version::$(node --version)"
    - name: Cache native node libraries
      uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: ~/node-gyp/cache
        key: ${{ runner.os }}-${{ github.job }}-${{ steps.nodeversion.outputs.node-version }}
    - name: Ensure node-gyp cache is populated
      if: matrix.os == 'windows-latest'
      run: |
          npm install -g node-gyp
          node-gyp install
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ github.job }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-${{ github.job }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ github.job }}-node-${{ hashFiles('examples/**/package.json', 'api/**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-node-
    - name: Cache cargo build
      if: matrix.os != 'macos-latest'
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ github.job }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ steps.nodeversion.outputs.node-version }}
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - name: Build
      uses: actions-rs/cargo@v1
      with:
          command: build
          args: --verbose --all-features
    - name: Check formatting
      if: matrix.os == 'ubuntu-20.04'
      uses: actions-rs/cargo@v1
      with:
          command: fmt
          args: -- --check
    - name: Check license headers
      if: matrix.os == 'ubuntu-20.04'
      run: cargo xtask check_license_headers --show-all
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
          command: test
          args: --verbose
    - name: Clean cache # Otherwise the cache is much too big
      if: matrix.os == 'ubuntu-20.04'
      run: |
          du -hs target
          rm -rf target/*/incremental
          rm -rf target/*/*/*sixtyfps*
          rm -rf target/*/*sixtyfps*
          rm -rf target/*/*/test* target/*/*/gallery* target/*/*/printerdemo* target/*/*/viewer* target/*/*/todo*
          rm -rf target/*/viewer target/*/printerdemo target/*/gallery target/*/todo target/*/*test*
          du -hs target

  cpp:
    env:
      LD_LIBRARY_PATH: /home/runner/work/sixtyfps/Qt/5.12.9/gcc_64/lib
      DYLD_FRAMEWORK_PATH: /Users/runner/work/sixtyfps/Qt/5.12.9/clang_64/lib
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt-get install libxcb-shape0-dev libxcb-xfixes0-dev
    - name: Cache Qt
      if: matrix.os != 'windows-latest'
      id: cache-qt
      uses: actions/cache@v2
      with:
        path: ../Qt
        key: ${{ runner.os }}-${{ github.job }}-QtCache-5.12.9
    - name: Install Qt
      if: matrix.os != 'windows-latest'
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.9'
        cached: ${{ steps.cache-qt.outputs.cache-hit }}
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ github.job }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-${{ github.job }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
    - uses: ilammy/msvc-dev-cmd@v1
    - name: Select MSVC (windows)
      run: |
        echo "CC=cl.exe" >> $GITHUB_ENV
        echo "CXX=cl.exe" >> $GITHUB_ENV
      if: matrix.os == 'windows-latest'
    - name: C++ Build
      uses: lukka/run-cmake@v2.4
      with:
        cmakeListsTxtPath: CMakeLists.txt
        buildDirectory: ${{ runner.workspace }}/cppbuild
    - name: cpack
      working-directory: ${{ runner.workspace }}/cppbuild
      run: cmake --build . --target package
    - name: "Upload C++ packages"
      uses: actions/upload-artifact@v2
      with:
          name: cpp_bin
          path: ${{ runner.workspace }}/cppbuild/SixtyFPS-*


  docs:
    runs-on: ubuntu-20.04
    env:
          RUSTDOCFLAGS: --html-in-header=/home/runner/work/sixtyfps/sixtyfps/api/sixtyfps-rs/sixtyfps-docs-integration.html
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - id: nodeversion
      run: |
          echo "::set-output name=node-version::$(node --version)"
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ github.job }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-${{ github.job }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo build
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ github.job }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
          toolchain: nightly
    - name: Install doxygen
      run: sudo apt-get install doxygen
    - uses: dschep/install-pipenv-action@v1
    - name: Build Cpp docs
      run: cargo xtask cppdocs
    - name: "Rust docs"
      uses: actions-rs/cargo@v1
      with:
          command: doc
          toolchain: nightly
          args: -p sixtyfps -p sixtyfps-build -p pin-weak --no-deps
    - name: "Node docs"
      run: |
          npm install --ignore-scripts
          npm run docs
      working-directory: api/sixtyfps-node
    - name: "Upload Docs Artifacts"
      uses: actions/upload-artifact@v2
      with:
          name: docs
          path: |
              target/doc
              target/cppdocs/html
              api/sixtyfps-node/docs
  wasm:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - id: nodeversion
      run: |
          echo "::set-output name=node-version::$(node --version)"
    - name: Cache native node libraries
      uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: ~/node-gyp/cache
        key: ${{ runner.os }}-${{ github.job }}-${{ steps.nodeversion.outputs.node-version }}
    - name: Cache cargo registry
      uses: actions/cache@v2
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-${{ github.job }}-cargo-registry-${{ hashFiles('**/Cargo.toml') }}
    - name: Cache cargo index
      uses: actions/cache@v2
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-${{ github.job }}-cargo-index-${{ hashFiles('**/Cargo.toml') }}
    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-${{ github.job }}-node-${{ hashFiles('examples/**/package.json', 'api/**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-node-
    - name: Cache cargo build
      uses: actions/cache@v2
      with:
        path: target
        key: ${{ runner.os }}-${{ github.job }}-cargo-build-target-${{ hashFiles('**/Cargo.toml') }}-${{ steps.nodeversion.outputs.node-version }}
    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          override: true
          components: rustfmt, clippy
          target: wasm32-unknown-unknown
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: Compile sixtyfps-wasm-interpreter
      run: wasm-pack build --release --target web -- --features console_error_panic_hook
      working-directory: api/sixtyfps-wasm-interpreter
    - name: Compile online editor
      run: |
          npm install
          npm run build
      working-directory: tools/online_editor
    - name: Gallery WASM build
      run: |
          npm install
          npm run build
      working-directory: examples/gallery/wasm
    - name: Printer demo WASM build
      run: |
          npm install
          npm run build
      working-directory: examples/printerdemo/wasm
    - name: Todo demo WASM build
      run: |
          npm install
          npm run build
      working-directory: examples/todo/wasm
    - name: "Upload Demo Artifacts"
      uses: actions/upload-artifact@v2
      with:
          name: wasm
          path: |
              examples/gallery/wasm/dist/
              examples/printerdemo/wasm/dist/
              examples/todo/wasm/dist/
              api/sixtyfps-wasm-interpreter/pkg/
              tools/online_editor/dist/
    - name: Clean cache # Otherwise the cache is much too big
      run: |
          du -hs target
          rm -rf target/*/incremental
          rm -rf target/*/*/*sixtyfps*
          du -hs target

  publish:
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    needs: [build_and_test, cpp, docs, wasm] # also depends on build_and_test and cpp to only publish if tests are green
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: docs
      - uses: actions/download-artifact@v2
        with:
          name: wasm
      - name: Publish Docs and Demos
        run: |
            git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
            git config --global user.name "${GITHUB_ACTOR}"
            git clone "https://tronical:${{ secrets.WWW_PUBLISH_SECRET }}@github.com/sixtyfpsui/www"
            cd www
            rm -rf demos
            mkdir -p demos
            mkdir -p demos/gallery
            mkdir -p demos/printerdemo
            mkdir -p demos/todo
            cp -a ../examples/gallery/wasm/dist/* demos/gallery/
            cp -a ../examples/printerdemo/wasm/dist/* demos/printerdemo/
            cp -a ../examples/todo/wasm/dist/* demos/todo/
            git add demos
            git add -u demos
            rm -rf wasm-interpreter
            mkdir -p wasm-interpreter
            cp -a ../api/sixtyfps-wasm-interpreter/pkg/* ./wasm-interpreter/
            git add wasm-interpreter
            git add -u wasm-interpreter
            rm -rf editor
            mkdir -p editor
            cp -a ../tools/online_editor/dist/* editor/
            git add editor
            git add -u editor
            rm -rf docs
            mkdir -p docs
            mkdir -p docs/cpp
            cp -a ../target/cppdocs/html/* docs/cpp/
            mkdir -p docs/rust
            cp -a ../target/doc/* docs/rust/
            mkdir -p docs/node
            cp -a ../api/sixtyfps-node/docs/* docs/node/
            git add docs
            git add -u docs
            git commit --message "Update $NAME from $GITHUB_REPOSITORY" --message "Pull web demos and C++/Rust reference docs from commit $GITHUB_SHA ($GITHUB_REF)"
            git push origin master


